### ISSUE TITLE
destination segment starts from wrong point

### ISSUE THREAD

**Issue by 2813** [JJWW-osm/josm-makeparallel#1]
Sometimes, the second point (begging of destination segment) changes its position.

for example. the second point was UNDER the source segment, and after transformation (makeparrallel) became OVER the source segment.
![mapparallel1](https://user-images.githubusercontent.com/33102505/105131867-d8c44f80-5afa-11eb-8364-c1fdc4d0e932.gif)

**Comment by 2813** [comment]
![mapparallel1](https://user-images.githubusercontent.com/33102505/105131838-ca763380-5afa-11eb-9027-f909ca31da26.gif)

**Comment by JJWW-osm** [comment]
This is hopefully fixed in version v1.1.0
